#!/usr/bin/env python3
"""Generate limits_generated.py from CloudFormation registry resource schemas.

Sources (pick one):
  --from-cfnlint          use the schema set vendored inside the installed cfn-lint
                          package (default; refresh by `pip install -U cfn-lint`)
  --from-url URL          download AWS's official bundle, e.g.
                          https://schema.cloudformation.us-east-1.amazonaws.com/CloudformationSchema.zip
  --from-dir PATH         directory of per-type *.json registry schemas

Selection heuristic (deliberately conservative):
  top-level string property with a maxLength whose name ends in
  "Name" / "Identifier" / "AliasName" / "Family", excluding plural "Names"
  and read-only properties. Curated entries in limits.py always override
  generated ones on conflict, so hand-verified corrections win.

Usage:
  python tools/generate_limits.py --from-cfnlint \
      -o python/cfn_name_check/limits_generated.py
"""
from __future__ import annotations
import argparse, io, json, os, re, sys, zipfile
from datetime import date

NAME_SUFFIXES = ("Name", "Identifier", "AliasName", "Family")
EXCLUDE_SUFFIXES = ("Names",)
LOWERCASE_HINT = re.compile(r"a-z")
UPPERCASE_HINT = re.compile(r"A-Z|\\w|\\S")


def iter_schemas_cfnlint(region="us-east-1"):
    import cfnlint  # noqa
    root = os.path.join(os.path.dirname(cfnlint.__file__), "data", "schemas")
    region_file = os.path.join(root, "providers", f"{region}.json")
    if os.path.exists(region_file):  # cfn-lint >= 1.x consolidated layout
        mapping = json.load(open(region_file, encoding="utf-8"))
        for type_name, h in mapping.items():
            path = os.path.join(root, "resources", f"{h}.json")
            if os.path.exists(path):
                yield json.load(open(path, encoding="utf-8"))
    else:  # older per-file layout
        d = os.path.join(root, "providers", region.replace("-", "_"))
        for f in sorted(os.listdir(d)):
            if f.endswith(".json"):
                yield json.load(open(os.path.join(d, f), encoding="utf-8"))


def iter_schemas_zip(url):
    from urllib.request import urlopen
    data = urlopen(url).read()
    zf = zipfile.ZipFile(io.BytesIO(data))
    for name in zf.namelist():
        if name.endswith(".json"):
            yield json.loads(zf.read(name))


def iter_schemas_dir(path):
    for f in sorted(os.listdir(path)):
        if f.endswith(".json"):
            try:
                yield json.load(open(os.path.join(path, f), encoding="utf-8"))
            except json.JSONDecodeError:
                continue


def _deref(schema, pdef, depth=0):
    """Resolve local #/definitions/... $ref chains (with cycle/depth guard)."""
    while isinstance(pdef, dict) and "$ref" in pdef and depth < 5:
        ref = pdef["$ref"]
        if not ref.startswith("#/"):
            return pdef
        node = schema
        for part in ref[2:].split("/"):
            node = node.get(part) if isinstance(node, dict) else None
            if node is None:
                return pdef
        pdef, depth = node, depth + 1
    return pdef


def extract(schemas):
    out = {}
    n_props = 0
    for schema in schemas:
        type_name = schema.get("typeName")
        props = schema.get("properties")
        if not type_name or not isinstance(props, dict):
            continue
        read_only = set(schema.get("readOnlyProperties") or [])
        create_only = set(schema.get("createOnlyProperties") or [])
        entries = []
        for pname, pdef in props.items():
            if not isinstance(pdef, dict):
                continue
            if not pname.endswith(NAME_SUFFIXES) or pname.endswith(EXCLUDE_SUFFIXES):
                continue
            ppath = f"/properties/{pname}"
            # Some schemas mark settable names as readOnly AND createOnly;
            # only a pure readOnly property is truly not user-settable.
            if ppath in read_only and ppath not in create_only:
                continue
            pdef = _deref(schema, pdef)
            if not isinstance(pdef, dict):
                continue
            ptype = pdef.get("type", "string")
            max_len = pdef.get("maxLength")
            if ptype != "string" or not isinstance(max_len, int):
                continue
            cons = {}
            pattern = pdef.get("pattern") or ""
            if pattern and LOWERCASE_HINT.search(pattern) and not UPPERCASE_HINT.search(pattern):
                cons["lowercase"] = True
            entries.append((pname, max_len,
                            f"{pname} ({type_name.split('::')[1]} registry limit)", cons))
            n_props += 1
        if entries:
            out[type_name] = sorted(entries)
    return out, n_props


HEADER = '''"""AUTO-GENERATED by tools/generate_limits.py — do not edit by hand.

Source: CloudFormation registry resource schemas ({source})
Generated: {today} | {n_types} resource types, {n_props} name properties.

Curated entries in limits.py override these on conflict.
Regenerate: python tools/generate_limits.py --from-cfnlint -o cfn_name_check/limits_generated.py
"""

GENERATED = {{
'''


def main(argv=None):
    ap = argparse.ArgumentParser()
    src = ap.add_mutually_exclusive_group()
    src.add_argument("--from-cfnlint", action="store_true", default=True)
    src.add_argument("--from-url")
    src.add_argument("--from-dir")
    ap.add_argument("--region", default="us-east-1")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args(argv)

    if args.from_url:
        schemas, source = iter_schemas_zip(args.from_url), args.from_url
    elif args.from_dir:
        schemas, source = iter_schemas_dir(args.from_dir), args.from_dir
    else:
        import cfnlint
        schemas = iter_schemas_cfnlint(args.region)
        source = f"cfn-lint {cfnlint.version.__version__} vendored set, {args.region}"

    limits, n_props = extract(schemas)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(HEADER.format(source=source, today=date.today(),
                              n_types=len(limits), n_props=n_props))
        for type_name in sorted(limits):
            f.write(f"    {type_name!r}: [\n")
            for pname, max_len, note, cons in limits[type_name]:
                f.write(f"        ({pname!r}, {max_len}, {note!r}, {cons!r}),\n")
            f.write("    ],\n")
        f.write("}\n")
    print(f"wrote {args.output}: {len(limits)} types, {n_props} name properties (source: {source})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
